---
title: "Untitled"
author: "Alina Bollhagen"
date: "2023-03-30"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r Library and data loading}

# Load libraries
library(SingleCellExperiment)
library(tidyverse)
library(imcRtools)
library(pheatmap)
library(viridis)
library(edgeR)
library(BiocParallel)
library(igraph)
library(corrr)
library(ggraph)
library(spicyR)
library(ggplot2)
library(ComplexHeatmap)
library(ade4)
library(DGCA)

# Read SingleCellExperiment objects
sce_tumor <- readRDS("/Volumes/G_DQBM_BB_Central$/projects/BCmet/workflowr_publication/BCmet_pub/output/SCEs/tumor/tumorSCE_initial_clustered_with_tumor_clusters.rds")
sce_Tcells <- readRDS("/Volumes/G_DQBM_BB_Central$/projects/BCmet/workflowr_publication/BCmet_pub/output/SCEs/Tcell/TcellSCE_subclustered.rds")
sce_myeloid <- readRDS("/Volumes/G_DQBM_BB_Central$/projects/BCmet/workflowr_publication/BCmet_pub/output/SCEs/myeloid/myeloidSCE_subclustered.rds")

sce_tumor$ROI <- substr(sce_tumor$ROI_ID, 1,14)
sce_Tcells$ROI <- substr(sce_Tcells$ROI_ID, 1,14)
sce_myeloid$ROI <- substr(sce_myeloid$ROI_ID, 1,14)

# Extract epithelial, endothelial, B cells and stroma from tumor SCE, T cells and myeloid cells
sce_tumor <- sce_tumor[,which(sce_tumor$celltype %in% c("Epithelial", "Endothelial", "Stroma"))]
sce_Tcells <- sce_Tcells[,which(sce_Tcells$celltype %in% c("NK_cell", "T_cell", "plasma_cell", "B_cell"))]
sce_Tcells <- sce_Tcells[,-which(sce_Tcells$celltype == "T_cell" & sce_Tcells$Tcell_subtype == "none")]
sce_myeloid <- sce_myeloid[,which(!(sce_myeloid$M_cluster %in% "none"))]

# Name tumor clusters
tumor_clusters <- tumor_clusters <- c("CK+ HER2+", "CK+ ER+ 1", "CK+ mTOR+", "CK+ HRhigh","EGFR+", 
                    "CK7+ CK+", "CK+ ER+ 2", "anti-apoptotic", "EGFR+ p53+", "proliferative", 
                    "immune-evasive", "CKlow ER+", "apoptotic", "hypoxic", "myoepithelial 2", 
                    "CK+ HRlow", "basal", "myoepithelial 1", "CKlow HER2+", "epitheliallow")
names(tumor_clusters) <- as.character(c(1:20))

cols_tumor_clusters <- c("#FF9900", "#FF6600", "#993300", "#663300", "#996666",
                                  "#CC3300", "#660000", "#993333", "#990000", "#CC0000",
                                  "#FF3333", "#990033", "#FF3399", "#CC0066", "#CC9933",
                                  "#CC6600", "#FF3366", "#FF3300", "#330000", "#CC9966")

# Name myeloid clusters
myeloid_clusters <- c("ARG1+ myeloid", "ap myeloid", "myeloid 1", "pro-inflammatory macrophages", 
                      "immunomodulatory myeloid", "macrophages 1", "myeloid 2", "MMP9+ macrophages",
                      "monocytes 1", "STING+ DC", "cDC1", "cDC2",
                      "TAMs", "monocytes 2", "immunosuppressive myeloid", "macrophages 2",
                      "moDC", "LAMP3 DC", "neutrophils", "pDC")
names(myeloid_clusters) <- c("M_c1", "M_c2", "M_c3", "M_c4", 
                             "M_c5", "M_c6", "M_c7", "M_c8", 
                             "M_c9", "M_c10", "M_c11", "M_c12", 
                             "M_c13", "M_c14", "M_c15", "M_c16", "M_c17",
                             "LAMP3_DC", "neutrophil", "pDC")

cols_myeloid_clusters <- c("#663399", "#6600CC", "#330099", "#333366", 
                           "#9933FF", "#666699", "#333399", "#6666CC",
                           "#3333CC", "#6666FF", "#3399FF", "#33CCFF",
                           "#66CCFF", "#6699FF", "#3366FF", "#00CCFF",
                           "#0099FF", "#0066FF", "#000066", "#003366")
                           
names(cols_myeloid_clusters) <- myeloid_clusters
                           
# Name T cell clusters

immune_clusters <- c("B cells", "NK cells", "plasma cells")
names(immune_clusters) <- c("B_cell", "NK_cell", "plasma_cell")
cols_immune_clusters <- c("#003300", "#006633", "#009966")
names(cols_immune_clusters) <- immune_clusters

Tcell_clusters <- c("exhausted CD8 T cell", "Treg", "developing CD4 T cell", "CD4 Thelper cells",
                    "developing Treg", "effector CD8 T cell", "Tfh", "developing CD8 T cell", "cytotoxic CD8 T cell", 
                    "CD7 CD8 T cell", "activated CD8 T cell")

names(Tcell_clusters) <- c("CD8_exhausted", "Treg", "CD4_TCF7-high", "CD4_Thelper", 
                           "Treg-developing", "CD8_effector", "Tfh", "CD8_TCF7-high", 
                           "CD8_GZMB-high", "CD8_CD7-high", "CD8_activated")

cols_Tcell_clusters <- c("#33CC00", "#00CC33", "#339900", "#006600",
                         "#009933", "#336633", "#00FF66", "#00CC00",
                         "#669966", "#009900", "#99FF00")

names(cols_Tcell_clusters) <- Tcell_clusters

# Adapt cluster names
sce_tumor$celltype[which(sce_tumor$cell_class == "epithelial")] <- tumor_clusters[sce_tumor$celltypeTumorClusters[which(sce_tumor$cell_class == "epithelial")]]
sce_Tcells$celltype[which(sce_Tcells$celltype == "T_cell")] <- Tcell_clusters[sce_Tcells$Tcell_subtype[which(sce_Tcells$celltype == "T_cell")]]
sce_myeloid$celltype <- myeloid_clusters[sce_myeloid$M_cluster]

# Select intratumoral regions
#sce_tumor <- sce_tumor[,which(sce_tumor$Location == "intratumoral")]
#sce_Tcells <- sce_Tcells[,which(sce_Tcells$Location == "intratumoral")]
#sce_myeloid <- sce_myeloid[,which(sce_myeloid$Location == "intratumoral")]

sce_tumor$imageCellID <- sce_tumor$cellID
sce_tumor$cellID <- NULL

sce_Tcells$imageCellID <- sce_Tcells$cellID
sce_Tcells$cellID <- NULL

sce_myeloid$imageCellID <- sce_myeloid$cellID
sce_myeloid$cellID <- NULL

```


```{r}

#order is from top to bottom (based on the script TumorPanel_05_phenotypic_composition_analysis)
order <- c("ID32", "ID27", "ID13", "ID3",  "ID70", "ID37", "ID48", "ID43", 
           "ID10", "ID85", "ID47", "ID34", "ID55", "ID16", "ID46", "ID58", 
           "ID44", "ID56", "ID81", "ID6",  "ID41", "ID52", "ID14", "ID28", 
           "ID50", "ID45", "ID5",  "ID9",  "ID23", "ID7",  "ID40", "ID60", 
           "ID51", "ID33", "ID17", "ID22", "ID73", "ID42", "ID15", "ID68", 
           "ID29", "ID86", "ID84", "ID2",  "ID21", "ID67", "ID4",  "ID57", 
           "ID69", "ID38", "ID76", "ID71", "ID8",  "ID39", "ID54", "ID31", 
           "ID59", "ID87", "ID66", "ID11", "ID64", "ID19", "ID18", "ID79", 
           "ID88", "ID30", "ID65", "ID25", "ID24", "ID49", "ID72", "ID36", 
           "ID78")

metacluster <- c(rep("1",11), rep("2",6), rep("3",2), rep("4", 1), rep("5",4), rep("6",5),
                 rep("7",3), rep("8",7), rep("9",13), rep("10",2), rep("11",5),
                 rep("12",8), rep("13",5), rep("14",1))
names(metacluster) <- order

```


```{r Differential abundance in metastases}

tumor_PT <- sce_tumor[,which(sce_tumor$Tissue.Type %in% "PT")]
Tcells_PT <- sce_Tcells[,which(sce_Tcells$Tissue.Type %in% "PT")]
myeloids_PT <- sce_myeloid[,which(sce_myeloid$Tissue.Type %in% "PT")]

tumor_PT_abundances <- table(tumor_PT$celltype[which(tumor_PT$Location == "intratumoral")], tumor_PT$Patient.ID[which(tumor_PT$Location == "intratumoral")])
Tcells_abundances_PT_intra <- table(Tcells_PT$celltype[which(Tcells_PT$Location == "intratumoral")], Tcells_PT$Patient.ID[which(Tcells_PT$Location == "intratumoral")])
myeloid_abundances_PT_intra <- table(myeloids_PT$celltype[which(myeloids_PT$Location == "intratumoral")], myeloids_PT$Patient.ID[which(myeloids_PT$Location == "intratumoral")])

### METS
tumor_M <- sce_tumor[,which(sce_tumor$Tissue.Type %in% c("SoftTissue", "Brain", "Bone", "Liver"))]
Tcells_M <- sce_Tcells[,which(sce_Tcells$Tissue.Type %in% c("SoftTissue", "Liver", "Brain", "Bone"))]
myeloids_M <- sce_myeloid[,which(sce_myeloid$Tissue.Type %in% c("SoftTissue", "Brain", "Liver", "Bone"))]

tumor_M_abundances <- table(tumor_M$celltype[which(tumor_M$Location == "intratumoral")], tumor_M$Patient.ID[which(tumor_M$Location == "intratumoral")])
Tcells_abundances_M_intra <- table(Tcells_M$celltype[which(Tcells_M$Location == "intratumoral")], Tcells_M$Patient.ID[which(Tcells_M$Location == "intratumoral")])
myeloid_abundances_M_intra <- table(myeloids_M$celltype[which(myeloids_M$Location == "intratumoral")], myeloids_M$Patient.ID[which(myeloids_M$Location == "intratumoral")])
  
# Calculate intersect
common <- Reduce(intersect, list(colnames(tumor_PT_abundances), colnames(tumor_M_abundances),
                    colnames(Tcells_abundances_PT_intra), colnames(Tcells_abundances_M_intra),
                    colnames(myeloid_abundances_PT_intra), colnames(myeloid_abundances_M_intra)))

immune_abundances_PT <- rbind(Tcells_abundances_PT_intra[,common], myeloid_abundances_PT_intra[,common])
immune_abundances_M <- rbind(Tcells_abundances_M_intra[,common], myeloid_abundances_M_intra[,common])
tumor_abundances_PT <- tumor_PT_abundances[-c(15,22),common]
tumor_abundances_M <- tumor_M_abundances[-c(15,22),common]
immune_abundances_PT <- unclass(immune_abundances_PT)
immune_abundances_M <- unclass(immune_abundances_M)
tumor_abundances_PT <- unclass(tumor_abundances_PT)
tumor_abundances_M <- unclass(tumor_abundances_M)

# Prepare metadata
meta <- colData(Tcells_M)[match(colnames(tumor_abundances_PT), Tcells_M$Patient.ID),]
rownames(meta) <- meta$Patient.ID
cur_ab <- immune_abundances_PT[,rownames(meta)]

# add metacluster information
order <- c("ID53", "ID27", "ID32", "ID13",  "ID3", "ID37", "ID48", "ID10", #1
           "ID47", "ID77", "ID35", "ID34", #
           "ID78", 
           "ID36", "ID25", "ID24", "ID49", "ID72", 
           "ID11", "ID64",  "ID18", "ID79", "ID88", "ID30", "ID65", #4
           "ID34", "ID44", "ID58",  "ID55",  "ID16", "ID46",  #5
           "ID40", "ID60", #6
           "ID38", "ID57", "ID71", "ID76", "ID62", "ID4", "ID67", "ID21",
           "ID29", "ID86", "ID2", "ID85", "ID68", "ID84", #7
           "ID15", "ID42", "ID17", "ID70",  "ID22", "ID73", "ID7",  "ID33", "ID51", #8 
           "ID56", "ID75", "ID81", 
           "ID6", #10
           "ID41",  "ID52", "ID14", "ID28", #11
           "ID5", "ID45", "ID50", "ID23", "ID9", #12
           "ID66", 
           "ID66", "ID39", "ID31", "ID54", "ID59", "ID87" ) #2

metacluster <- c(rep("1",12), rep("2",1), rep("3",5), rep("4", 7), rep("5",6), rep("6",2),
                 rep("7",14), rep("8",9), rep("9",3), rep("10",1), rep("11",4),
                 rep("12",5), rep("13",1), rep("14",6))
names(metacluster) <- order

meta$metacluster <- metacluster[meta$Patient.ID]

# Generate logFC and sig object
logFC_M <- as.data.frame(matrix(nrow = length(rownames(immune_abundances_PT)), ncol =14))
rownames(logFC_M) <- rownames(immune_abundances_PT)
sig_M <- as.data.frame(matrix(nrow = length(rownames(immune_abundances_PT)), ncol =14))
rownames(sig_M) <- rownames(immune_abundances_PT)

for (i in 1:14) {
  meta$info <- as.character(meta$metacluster)
  meta$info[which(!(meta$info %in% as.character(i)))] <- "ref"
  info <- factor(meta$info)
  meta$info <- relevel(x=info, ref = "ref")
y <- DGEList(cur_ab, samples = meta, group = meta$info)

# Define the design matrix for the model: add tissue type as an additive factor
design <- model.matrix(~ 0 + Tissue.Type + info, data = y$samples)

# Estimate NB and QL dispersion
y <- estimateDisp(y, design, trend="none")
fit <- glmQLFit(y, design, robust=TRUE, abundance.trend=FALSE)

# Test for differential abundance of cell types 
res <- glmQLFTest(fit, coef=colnames(fit)[ncol(fit)])
summary(decideTests(res))
DA <- res$table
DA$celltype <- rownames(DA)

# Add to final objects
logFC_M[,i] <- DA[rownames(logFC_M), "logFC"]
sig_M[,i] <- DA[rownames(logFC_M), "PValue"]
  
}

```

```{r patient composition}

tumor_abundances_PT <- apply(tumor_abundances_PT, MARGIN = 2, FUN = function(x) x/sum(x))
tumor_abundances_M <- apply(tumor_abundances_M, MARGIN = 2, FUN = function(x) x/sum(x))
immune_abundances_PT <- apply(immune_abundances_PT, MARGIN = 2, FUN = function(x) x/sum(x))
immune_abundances_M <- apply(immune_abundances_M, MARGIN = 2, FUN = function(x) x/sum(x))


left_ha <- rowAnnotation(PT = anno_barplot(t(tumor_abundances_PT), width = unit(7, "cm"),
                                            bar_width = 1,
                                            gp = gpar(fill = c(cols_tumor_clusters),
                                                      col = alpha("white",0.5))),
                         M = anno_barplot(t(tumor_abundances_M), width = unit(7, "cm"),
                                            bar_width = 1,
                                            gp = gpar(fill = c(cols_tumor_clusters),
                                                      col = alpha("white",0.5))))

Heatmap(t(tumor_abundances_M),
        cluster_rows = TRUE,
        row_split = 14,
        left_annotation = left_ha,
        col = colorRamp2(c(0,0.5,1), c("white", "red", "darkred")))

order <- colnames(tumor_abundances_M)[row_order(a)]

Heatmap(t(immune_abundances_M)[order,],
        cluster_rows = FALSE,
        col = colorRamp2(c(0,0.5,1), c("white", "red", "darkred")))

```

