---
title: "Untitled"
author: "Alina Bollhagen"
date: "2024-01-03"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r Library and data loading}

# Load libraries
library(SingleCellExperiment)
library(tidyverse)
library(imcRtools)
library(pheatmap)
library(viridis)
library(edgeR)
library(BiocParallel)
library(igraph)
library(corrr)
library(ggraph)
library(spicyR)
library(ggplot2)
library(ComplexHeatmap)
library(ade4)

# Read SingleCellExperiment objects
sce_tumor <- readRDS("/Volumes/G_DQBM_BB_Central$/projects/BCmet/workflowr_publication/BCmet_pub/output/SCEs/tumor/tumorSCE_initial_clustered_with_tumor_clusters.rds")
sce_Tcells <- readRDS("/Volumes/G_DQBM_BB_Central$/projects/BCmet/workflowr_publication/BCmet_pub/output/SCEs/Tcell/TcellSCE_subclustered.rds")
sce_myeloid <- readRDS("/Volumes/G_DQBM_BB_Central$/projects/BCmet/workflowr_publication/BCmet_pub/output/SCEs/myeloid/myeloidSCE_subclustered.rds")

sce_tumor$ROI <- substr(sce_tumor$ROI_ID, 1,14)
sce_Tcells$ROI <- substr(sce_Tcells$ROI_ID, 1,14)
sce_myeloid$ROI <- substr(sce_myeloid$ROI_ID, 1,14)

# Extract epithelial, endothelial, B cells and stroma from tumor SCE, T cells and myeloid cells
#sce_tumor <- sce_tumor[,which(sce_tumor$celltype %in% c("Epithelial", "Endothelial", "Stroma"))]
sce_Tcells <- sce_Tcells[,which(sce_Tcells$celltype %in% c("NK_cell", "T_cell", "plasma_cell", "B_cell"))]
sce_Tcells <- sce_Tcells[,-which(sce_Tcells$celltype == "T_cell" & sce_Tcells$Tcell_subtype == "none")]
sce_myeloid <- sce_myeloid[,which(!(sce_myeloid$M_cluster %in% "none"))]

# Name tumor clusters
tumor_clusters <- tumor_clusters <- c("CK+ HER2+", "CK+ HR+ 1", "CK+ mTOR+", "CK+ HRhigh","EGFR+ hypoxic", 
                    "CK7+ CK+", "CK+ HR+ 2", "anti-apoptotic", "EGFR+ p53+", "proliferative", 
                    "immune-evasive", "CKlow HR+", "apoptotic", "hypoxic", "myoepithelial", 
                    "CK+ HRlow", "HLA-ABC+ basal", "basal", "CKlow HER2+", "epitheliallow")
names(tumor_clusters) <- as.character(c(1:20))

cols_tumor_clusters <- c("#680C07", "#BC544B", "#CC0000", "#9B2D1F", "#4E0707", 
                         "#D34817", "#FF6600", "#FA8128", "#FCAE1E", "#B56727",
                         "#80400B", "#D67229", "#330000", "#E3B778", "#FAE29C",
                         "#FDD0A2", "#C9BB8E", "#918485", "#FF3333", "#993300")

# Name myeloid clusters
myeloid_clusters <- c("ARG1+ myeloid", "ap myeloid", "proliferative myeloid", "pro-inflammatory macrophages", 
                      "IDO+ myeloid", "immunomod. macrophages 1", "myeloid", "MMP9+ macrophages",
                      "monocytes", "STING+ myeloid", "cDC1", "activated myeloid",
                      "immunomod. macrophages 2", "activated monocytes", "PD-L1+ hypoxic myeloid", "immunomod. macrophages 3",
                      "moDC", "LAMP3 DC", "neutrophils", "pDC")
names(myeloid_clusters) <- c("M_c1", "M_c2", "M_c3", "M_c4", 
                             "M_c5", "M_c6", "M_c7", "M_c8", 
                             "M_c9", "M_c10", "M_c11", "M_c12", 
                             "M_c13", "M_c14", "M_c15", "M_c16", "M_c17",
                             "LAMP3_DC", "neutrophil", "pDC")

cols_myeloid_clusters <- c("#663399", "#6600CC", "#330099", "#333366", 
                           "#9933FF", "#666699", "#333399", "#6666CC",
                           "#3333CC", "#6666FF", "#3399FF", "#33CCFF",
                           "#66CCFF", "#6699FF", "#3366FF", "#00CCFF",
                           "#0099FF", "#0066FF", "#000066", "#003366")
                           
names(cols_myeloid_clusters) <- myeloid_clusters
                           
# Name T cell clusters

immune_clusters <- c("B cells", "NK cells", "plasma cells")
names(immune_clusters) <- c("B_cell", "NK_cell", "plasma_cell")
cols_immune_clusters <- c("#003300", "#006633", "#009966")
names(cols_immune_clusters) <- immune_clusters

Tcell_clusters <- c("exhausted CD8 T cell", "Treg", "TCF7+ CD4 T cell", "CD4 Thelper cells",
                    "developing Treg", "effector CD8 T cell", "Tfh", "TCF7+ CD8 T cell", "cytotoxic CD8 T cell", 
                    "CD7 CD8 T cell", "activated CD8 T cell")

names(Tcell_clusters) <- c("CD8_exhausted", "Treg", "CD4_TCF7-high", "CD4_Thelper", 
                           "Treg-developing", "CD8_effector", "Tfh", "CD8_TCF7-high", 
                           "CD8_GZMB-high", "CD8_CD7-high", "CD8_activated")

cols_Tcell_clusters <- c("#33CC00", "#00CC33", "#339900", "#006600",
                         "#009933", "#336633", "#00FF66", "#00CC00",
                         "#669966", "#009900", "#99FF00")

names(cols_Tcell_clusters) <- Tcell_clusters

# Adapt cluster names
sce_tumor$celltype[which(sce_tumor$cell_class == "epithelial")] <- tumor_clusters[sce_tumor$celltypeTumorClusters[which(sce_tumor$cell_class == "epithelial")]]
sce_Tcells$celltype[which(sce_Tcells$celltype == "T_cell")] <- Tcell_clusters[sce_Tcells$Tcell_subtype[which(sce_Tcells$celltype == "T_cell")]]
sce_myeloid$celltype <- myeloid_clusters[sce_myeloid$M_cluster]

# Select intratumoral regions
sce_tumor <- sce_tumor[,which(sce_tumor$Location == "intratumoral")]
sce_Tcells <- sce_Tcells[,which(sce_Tcells$Location == "intratumoral")]
sce_myeloid <- sce_myeloid[,which(sce_myeloid$Location == "intratumoral")]

sce_tumor$imageCellID <- sce_tumor$cellID
sce_tumor$cellID <- NULL

sce_Tcells$imageCellID <- sce_Tcells$cellID
sce_Tcells$cellID <- NULL

sce_myeloid$imageCellID <- sce_myeloid$cellID
sce_myeloid$cellID <- NULL

```

```{r Median split time to relapse}

split <- distinct(as.data.frame(colData(sce_tumor[,which(sce_tumor$Tissue.Type == "PT")])[,c("Patient.ID", "Age.delta")]))
split <- median(as.numeric(split$Age.delta))
sce_tumor$relapse <- "late"
sce_myeloid$relapse <- "late"
sce_Tcells$relapse <- "late"
sce_tumor$relapse[which(as.numeric(sce_tumor$Age.delta) <= split)] <- "early"
sce_myeloid$relapse[which(as.numeric(sce_myeloid$Age.delta) <= split)] <- "early"
sce_Tcells$relapse[which(as.numeric(sce_Tcells$Age.delta) <= split)] <- "early"

```

```{r Differential abundance for myeloid cells}

sce_myeloid <- sce_myeloid[, which(sce_myeloid$M_cluster != "none")]
myeloids <- sce_myeloid[,which(sce_myeloid$Tissue.Type %in% c("PT"))]
myeloids <- myeloids[,which(myeloids$relapse != "NA")]
myeloids <- myeloids[,which(!(myeloids$celltype %in% "ARG1+ myeloid"))]
  
# Prepare abundance object
abundances <- table(myeloids$celltype, myeloids$Patient.ID)
abundances <- unclass(abundances)

meta <- colData(myeloids)[match(colnames(abundances), myeloids$Patient.ID),]
rownames(meta) <- meta$Patient.ID
cur_ab <- abundances[,rownames(meta)]


meta$info <- as.character(meta$relapse)
info <- factor(meta$info)
meta$info <- relevel(x=info, ref = "early")
y.ab <- DGEList(cur_ab, samples=meta, group = meta$info)

# Define the design matrix for the model: Add Patient ID to the model to account for matched design, add tissue type as an additive factor
design <- model.matrix(~molecular.subtype + info, data = y.ab$samples)

# Estimate NB and QL dispersion
y.ab <- estimateDisp(y.ab, design, trend="none")
summary(y.ab$common.dispersion)
fit.ab <- glmQLFit(y.ab, design, robust=TRUE, abundance.trend=FALSE)
summary(fit.ab$var.prior)


# Test for differential abundance of cell types in PT vs met tissue and plot
res <- glmQLFTest(fit.ab, coef=colnames(fit.ab)[ncol(fit.ab)])
summary(decideTests(res))
DA <- res$table

DA$celltype <- rownames(DA)
DA$sign <- ifelse(DA$PValue < 0.05, "yes", "no")

# Sort by logFC
order <- rev(rownames(DA))
DA$celltype <- factor(DA$celltype, levels = DA$celltype)

ggplot(DA, aes(celltype, y = logFC)) +
  geom_col(aes(fill = sign)) +
  scale_fill_manual(values = c("grey", "darkblue"))+
  labs(y = paste0("late vs. early"), x = "Cell type")+
  coord_flip() +
  labs(fill = "significant") +
  theme(panel.background=element_blank(), panel.border = element_rect(colour = "black", fill=NA, linewidth =1))


```


```{r Differential abundance for tumor cells}

sce_tumor_1 <- sce_tumor[,which(sce_tumor$cell_class == "epithelial")]
tumor <- sce_tumor_1[,which(sce_tumor_1$Tissue.Type %in% c("PT"))]
tumor <- tumor[,which(tumor$relapse != "NA")]
  
# Prepare abundance object
abundances <- table(tumor$celltype, tumor$Patient.ID)
abundances <- unclass(abundances)

meta <- colData(tumor)[match(colnames(abundances), tumor$Patient.ID),]
rownames(meta) <- meta$Patient.ID
cur_ab <- abundances[,rownames(meta)]

meta$info <- as.character(meta$relapse)
info <- factor(meta$info)
meta$info <- relevel(x=info, ref = "early")
y.ab <- DGEList(cur_ab, samples=meta, group = meta$info)

# Define the design matrix for the model: Add Patient ID to the model to account for matched design, add tissue type as an additive factor
design <- model.matrix(~molecular.subtype + info, data = y.ab$samples)

# Estimate NB and QL dispersion
y.ab <- estimateDisp(y.ab, design, trend="none")
summary(y.ab$common.dispersion)
fit.ab <- glmQLFit(y.ab, design, robust=TRUE, abundance.trend=FALSE)
summary(fit.ab$var.prior)


# Test for differential abundance of cell types in PT vs met tissue and plot
res <- glmQLFTest(fit.ab, coef=colnames(fit.ab)[ncol(fit.ab)])
summary(decideTests(res))
DA <- res$table

DA$celltype <- rownames(DA)
DA$sign <- ifelse(DA$PValue < 0.05, "yes", "no")

# Sort by logFC
order <- rev(rownames(DA))
DA$celltype <- factor(DA$celltype, levels = DA$celltype)

ggplot(DA, aes(celltype, y = logFC)) +
  geom_col(aes(fill = sign)) +
  scale_fill_manual(values = c("grey", "darkblue"))+
  labs(y = paste0("late vs. early"), x = "Cell type")+
  coord_flip() +
  labs(fill = "significant") +
  theme(panel.background=element_blank(), panel.border = element_rect(colour = "black", fill=NA, linewidth =1))

  
```


```{r Differential abundance for T cells}

sce_Tcells <- sce_Tcells[,which(sce_Tcells$cell_class == "immune" & sce_Tcells$celltype != "myeloid" & 
                                  sce_Tcells$celltype != "neutrophil" & sce_Tcells$celltype != "HLA-DR_high")]
Tcells <- sce_Tcells[,which(sce_Tcells$Tissue.Type %in% c("PT"))]
Tcells <- Tcells[,which(Tcells$relapse != "NA")]
  
# Prepare abundance object
abundances <- table(Tcells$celltype, Tcells$Patient.ID)
abundances <- unclass(abundances)

meta <- colData(Tcells)[match(colnames(abundances), Tcells$Patient.ID),]
rownames(meta) <- meta$Patient.ID
cur_ab <- abundances[,rownames(meta)]


meta$info <- as.character(meta$relapse)
info <- factor(meta$info)
meta$info <- relevel(x=info, ref = "early")
y.ab <- DGEList(cur_ab, samples=meta, group = meta$info)

# Define the design matrix for the model: Add Patient ID to the model to account for matched design, add tissue type as an additive factor
design <- model.matrix(~molecular.subtype + info, data = y.ab$samples)

# Estimate NB and QL dispersion
y.ab <- estimateDisp(y.ab, design, trend="none")
summary(y.ab$common.dispersion)
fit.ab <- glmQLFit(y.ab, design, robust=TRUE, abundance.trend=FALSE)
summary(fit.ab$var.prior)


# Test for differential abundance of cell types in PT vs met tissue and plot
res <- glmQLFTest(fit.ab, coef=colnames(fit.ab)[ncol(fit.ab)])
summary(decideTests(res))
DA <- res$table

DA$celltype <- rownames(DA)
DA$sign <- ifelse(DA$PValue < 0.05, "yes", "no")

# Sort by logFC
order <- rev(rownames(DA))
DA$celltype <- factor(DA$celltype, levels = DA$celltype)

ggplot(DA, aes(celltype, y = logFC)) +
  geom_col(aes(fill = sign)) +
  scale_fill_manual(values = c("grey", "darkblue"))+
  labs(y = paste0("late vs. early"), x = "Cell type")+
  coord_flip() +
  labs(fill = "significant") +
  theme(panel.background=element_blank(), panel.border = element_rect(colour = "black", fill=NA, linewidth =1))

```

```{r}

input <- distinct(as.data.frame(colData(sce_tumor[,which(sce_tumor$Tissue.Type == "PT")])[,c("Patient.ID", "Age.delta", "Site.of.metastasis", "molecular.subtype")]))

input$Age.delta <- as.numeric(input$Age.delta)

ggplot(input, aes(x = Age.delta, fill = molecular.subtype)) +
  geom_bar() +
  theme(panel.background=element_blank(), panel.border = element_rect(colour = "black", fill=NA, linewidth =1))

```

```{r spicyR}

spicyTest <- spicy(sce_tumor,
                   condition = "sample_type",
                   subject = "Patient.ID",
                   imageID = "ROI_ID",
                   cellType = "celltype",
                   imageCellID = "imageCellID",
                   spatialCoords = c("Center_X", "Center_Y"))

topPairs(spicyTest)
signifPlot(spicyTest, 
           marksToPlot = c("B-cells", "CD4 T-cells", "CD8 T-cells", "Stroma", "Endothelial", "anti-apoptotic",
                                            "apoptotic", "basal", "CK+ HER2+", "CK+ HR+ 1", "CK+ HR+ 2", "CK+ HRlow", "CK+ mTOR+",
                                            "CK7+, CK+", "CKlow HER2+", "CKlow HR+", "EGFR+ hypoxic", "EGFR+ p53+", "epitheliallow",
                                            "HLA-ABC+ basal", "hypoxic", "immune-evasive", "myoepithelial", "proliferative", "Myeloid"))

```

```{r absolute numbers}

sce_Tcells$cell_population <- sce_Tcells$cell_class
sce_Tcells$cell_population[which(sce_Tcells$cell_class %in% c("stromal", "undefined"))] <- "other"
sce_Tcells$cell_population <- factor(sce_Tcells$cell_population, levels = c("epithelial", "immune", "other"))
sce_Tcells$Tissue.Type <- factor(sce_Tcells$Tissue.Type, levels = c("PT", "Bone", "Brain", "Liver", "SoftTissue"))

subset <- sce_tumor[,which(sce_tumor$Location == "intratumoral")]
input <- as.data.frame(unclass(table(subset$ROI)))
colD <- distinct(as.data.frame(colData(subset)[,c("ROI", "Tissue.Type")]))

input <- input[colD$ROI, , drop = FALSE]
input$Tissue.Type <- colD$Tissue.Type
colnames(input)[1] <- "cell_count"

ggplot(input, aes(x = Tissue.Type, y = log(cell_count), fill = Tissue.Type, color = Tissue.Type)) +
  geom_boxplot(alpha = 0.3) +
  scale_fill_manual(values = c("aquamarine4", "green3", "black", "skyblue", "grey")) +
  scale_color_manual(values = c("aquamarine4", "green3", "black", "skyblue", "grey")) +
  theme(panel.background=element_blank(), panel.border = element_rect(colour = "black", fill=NA, linewidth =1))


subset <- sce_myeloid[,which(sce_myeloid$Location == "intratumoral")]
input <- as.data.frame(unclass(table(subset$ROI, subset$cell_population)))
colD <- distinct(as.data.frame(colData(subset)[,c("ROI", "Tissue.Type")]))

input <- input[colD$ROI, , drop = FALSE]
input$Tissue.Type <- colD$Tissue.Type
data_long <- gather(input, cell_class, cell_count, 1:3, factor_key = TRUE)

ggplot(data_long, aes(x = cell_class, y = log(cell_count), fill = Tissue.Type, color = Tissue.Type)) +
  geom_boxplot(alpha = 0.3) +
  scale_fill_manual(values = c("aquamarine4", "green3", "black", "skyblue", "grey")) +
  scale_color_manual(values = c("aquamarine4", "green3", "black", "skyblue", "grey")) +
  theme(panel.background=element_blank(), panel.border = element_rect(colour = "black", fill=NA, linewidth =1))

```









