---
title: '05'
author: "Alina Bollhagen"
date: "2023-03-06"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Tumor communities

```{r Data input and package loading}

# Load libraries
library(SingleCellExperiment)
library(tidyverse)
library(imcRtools)
library(pheatmap)
library(viridis)
library(edgeR)
library(bluster)
library(BiocParallel)
library(igraph)
library(circlize)
library(bluster)

# Read SingleCellExperiment object with subclustered epithelial cells
# sce2 and sce_1 contains original clusters containing all cellclasses
# use sce_1 for downstream analysis
sce_tumor <- readRDS("/Volumes/G_DQBM_BB_Central$/projects/BCmet/workflowr_publication/BCmet_pub/output/SCEs/tumor/tumorSCE_initial_clustered_with_tumor_clusters.rds")
sce_myeloid <- readRDS("/Volumes/G_DQBM_BB_Central$/projects/BCmet/workflowr_publication/BCmet_pub/output/SCEs/myeloid/myeloidSCE_subclustered.rds")
sce_Tcells <- readRDS("/Volumes/G_DQBM_BB_Central$/projects/BCmet/workflowr_publication/BCmet_pub/output/SCEs/Tcell/TcellSCE_subclustered.rds")

# Name tumor clusters
tumor_clusters <- tumor_clusters <- c("CK+ HER2+", "CK+ ER+ 1", "CK+ mTOR+", "CK+ HRhigh","EGFR+", 
                    "CK7+ CK+", "CK+ ER+ 2", "anti-apoptotic", "EGFR+ p53+", "proliferative", 
                    "immune-evasive", "CKlow ER+", "apoptotic", "hypoxic", "myoepithelial 2", 
                    "CK+ HRlow", "basal", "myoepithelial 1", "CKlow HER2+", "epitheliallow")
names(tumor_clusters) <- as.character(c(1:20))

cols_tumor_clusters <- cols_tumor_clusters <-  c("#D34817", "#9B2D1F", "#FCAE1E", "#FF6600", "#330000", 
                         "#80400B", "#4E0707", "#680C07", "#E3B778", "#FDD0A2",
                         "#C9BB8E", "#993300", "#BC544B", "#B56727", "#FF3333",
                         "#FA8128", "#CC0000", "#918485", "#D67229", "#FAE29C")
names(cols_tumor_clusters) <- tumor_clusters

# Name myeloid clusters
myeloid_clusters <- c("ARG1+ myeloid", "ap myeloid", "myeloid 1", "pro-inflammatory macrophages", 
                      "immunomodulatory myeloid", "macrophages 1", "myeloid 2", "MMP9+ macrophages",
                      "monocytes 1", "STING+ DC", "cDC1", "cDC2",
                      "TAMs", "monocytes 2", "immunosuppressive myeloid", "macrophages 2",
                      "moDC", "LAMP3 DC", "neutrophils", "pDC")
names(myeloid_clusters) <- c("M_c1", "M_c2", "M_c3", "M_c4", 
                             "M_c5", "M_c6", "M_c7", "M_c8", 
                             "M_c9", "M_c10", "M_c11", "M_c12", 
                             "M_c13", "M_c14", "M_c15", "M_c16", "M_c17",
                             "LAMP3_DC", "neutrophil", "pDC")

cols_myeloid_clusters <- c("#CC3366", "#993399", "grey88", "#333366", 
                           "#9933FF", "#666699", "#333399", "#6666CC",
                           "#3333CC", "#FFCCCC", "#FF0099", "#00FFFF",
                           "#FF9999", "#6699FF", "#3333CC", "#00CCFF",
                           "#0099FF", "#0066FF", "#000066", "#000033")
                           
names(cols_myeloid_clusters) <- myeloid_clusters
                           
# Name T cell clusters

Tcell_clusters <- c("exhausted CD8 T cell", "Treg", "developing CD4 T cell", "CD4 Thelper cells",
                    "developing Treg", "effector CD8 T cell", "Tfh", "developing CD8 T cell", "cytotoxic CD8 T cell", 
                    "CD7 CD8 T cell", "activated CD8 T cell")

names(Tcell_clusters) <- c("CD8_exhausted", "Treg", "CD4_TCF7-high", "CD4_Thelper", 
                           "Treg-developing", "CD8_effector", "Tfh", "CD8_TCF7-high", 
                           "CD8_GZMB-high", "CD8_CD7-high", "CD8_activated")

cols_Tcell_clusters <- c("#33CC00", "#00CC33", "#339900", "#006600",
                         "#009933", "#336633", "#00FF66", "#00CC00",
                         "#669966", "#009900", "#99FF00")

names(cols_Tcell_clusters) <- Tcell_clusters

```

```{r Library and data loading}

# Load libraries
library(SingleCellExperiment)
library(tidyverse)
library(imcRtools)
library(pheatmap)
library(viridis)
library(edgeR)
library(BiocParallel)
library(igraph)
library(corrr)
library(ggraph)
library(spicyR)
library(ggplot2)
library(ComplexHeatmap)
library(ade4)

# Read SingleCellExperiment objects
sce_tumor <- readRDS("/Volumes/G_DQBM_BB_Central$/projects/BCmet/workflowr_publication/BCmet_pub/output/SCEs/tumor/tumorSCE_initial_clustered_with_tumor_clusters.rds")
sce_Tcells <- readRDS("/Volumes/G_DQBM_BB_Central$/projects/BCmet/workflowr_publication/BCmet_pub/output/SCEs/Tcell/TcellSCE_subclustered.rds")
sce_myeloid <- readRDS("/Volumes/G_DQBM_BB_Central$/projects/BCmet/workflowr_publication/BCmet_pub/output/SCEs/myeloid/myeloidSCE_subclustered.rds")

sce_tumor$ROI <- substr(sce_tumor$ROI_ID, 1,14)
sce_Tcells$ROI <- substr(sce_Tcells$ROI_ID, 1,14)
sce_myeloid$ROI <- substr(sce_myeloid$ROI_ID, 1,14)

# Name tumor clusters
tumor_clusters <- tumor_clusters <- c("CK+ HER2+", "CK+ HR+ 1", "CK+ mTOR+", "CK+ HRhigh","EGFR+ hypoxic", 
                    "CK7+ CK+", "CK+ HR+ 2", "anti-apoptotic", "EGFR+ p53+", "proliferative", 
                    "immune-evasive", "CKlow HR+", "apoptotic", "hypoxic", "myoepithelial", 
                    "CK+ HRlow", "HLA-ABC+ basal", "basal", "CKlow HER2+", "epitheliallow")
names(tumor_clusters) <- as.character(c(1:20))

cols_tumor_clusters <- c("#680C07", "#BC544B", "#CC0000", "#9B2D1F", "#4E0707", 
                         "#D34817", "#FF6600", "#FA8128", "#FCAE1E", "#B56727",
                         "#80400B", "#D67229", "#330000", "#E3B778", "#FAE29C",
                         "#FDD0A2", "#C9BB8E", "#918485", "#FF3333", "#993300")
names(cols_tumor_clusters) <- tumor_clusters

# Name myeloid clusters
myeloid_clusters <- c("ARG1+ myeloid", "ap myeloid", "proliferative myeloid", "pro-inflammatory macrophages", 
                      "IDO+ myeloid", "immunomod. macrophages 1", "myeloid", "MMP9+ macrophages",
                      "monocytes", "STING+ myeloid", "cDC1", "activated myeloid",
                      "immunomod. macrophages 2", "activated monocytes", "PD-L1+ hypoxic myeloid", "immunomod. macrophages 3",
                      "moDC", "LAMP3 DC", "neutrophils", "pDC")
names(myeloid_clusters) <- c("M_c1", "M_c2", "M_c3", "M_c4", 
                             "M_c5", "M_c6", "M_c7", "M_c8", 
                             "M_c9", "M_c10", "M_c11", "M_c12", 
                             "M_c13", "M_c14", "M_c15", "M_c16", "M_c17",
                             "LAMP3_DC", "neutrophil", "pDC")

cols_myeloid_clusters <- c("#663399", "#6600CC", "#330099", "#333366", 
                           "#9933FF", "#666699", "#333399", "#6666CC",
                           "#3333CC", "#6666FF", "#3399FF", "#33CCFF",
                           "#66CCFF", "#6699FF", "#3366FF", "#00CCFF",
                           "#0099FF", "#0066FF", "#000066", "#003366")
                           
names(cols_myeloid_clusters) <- myeloid_clusters
                           
# Name T cell clusters

immune_clusters <- c("B cells", "NK cells", "plasma cells")
names(immune_clusters) <- c("B_cell", "NK_cell", "plasma_cell")
cols_immune_clusters <- c("#003300", "#006633", "#009966")
names(cols_immune_clusters) <- immune_clusters

Tcell_clusters <- c("exhausted CD8 T cell", "Treg", "TCF7+ CD4 T cell", "CD4 Thelper cells",
                    "developing Treg", "effector CD8 T cell", "Tfh", "TCF7+ CD8 T cell", "cytotoxic CD8 T cell", 
                    "CD7 CD8 T cell", "activated CD8 T cell")

names(Tcell_clusters) <- c("CD8_exhausted", "Treg", "CD4_TCF7-high", "CD4_Thelper", 
                           "Treg-developing", "CD8_effector", "Tfh", "CD8_TCF7-high", 
                           "CD8_GZMB-high", "CD8_CD7-high", "CD8_activated")

cols_Tcell_clusters <- c("#33CC00", "#00CC33", "#339900", "#006600",
                         "#009933", "#336633", "#00FF66", "#00CC00",
                         "#669966", "#009900", "#99FF00")

names(cols_Tcell_clusters) <- Tcell_clusters

# Adapt cluster names
sce_tumor$celltype[which(sce_tumor$cell_class == "epithelial")] <- tumor_clusters[sce_tumor$celltypeTumorClusters[which(sce_tumor$cell_class == "epithelial")]]
sce_Tcells$celltype[which(sce_Tcells$celltype == "T_cell")] <- Tcell_clusters[sce_Tcells$Tcell_subtype[which(sce_Tcells$celltype == "T_cell")]]
sce_myeloid$celltype <- myeloid_clusters[sce_myeloid$M_cluster]

# Select intratumoral regions
sce_tumor <- sce_tumor[,which(sce_tumor$Location == "intratumoral")]
sce_Tcells <- sce_Tcells[,which(sce_Tcells$Location == "intratumoral")]
sce_myeloid <- sce_myeloid[,which(sce_myeloid$Location == "intratumoral")]

sce_tumor$imageCellID <- sce_tumor$cellID
sce_tumor$cellID <- NULL

sce_Tcells$imageCellID <- sce_Tcells$cellID
sce_Tcells$cellID <- NULL

sce_myeloid$imageCellID <- sce_myeloid$cellID
sce_myeloid$cellID <- NULL

```

## Spatial graph building

In the next section, we will define cellular neighborhoods by clustering
cells based on their neighboring cells. For this, we will only look at the intratumoral punches

```{r Spatial grapth building}

# Build expansion graphs
sce_tumor <- buildSpatialGraph(sce_tumor, img_id = "ImageNumber", type = "expansion", 
                             threshold = 60, 
                             coords = c("Center_X",  "Center_Y"),
                             name = "expansion_60")

sce_Tcells <- buildSpatialGraph(sce_Tcells, img_id = "ImageNumber", type = "expansion", 
                             threshold = 60, 
                             coords = c("Center_X",  "Center_Y"),
                             name = "expansion_60")

sce_myeloid <- buildSpatialGraph(sce_myeloid, img_id = "ImageNumber", type = "expansion", 
                             threshold = 60, 
                             coords = c("Center_X",  "Center_Y"),
                             name = "expansion_60")

```

We will now only focus on epithelial cells of these images

```{r}

sce_tumor <- sce_tumor[,sce_tumor$cell_class == "epithelial"]
sce_Tcells <- sce_Tcells[,(!(sce_Tcells$Tcell_subtype == "none"))]
sce_myeloid <- sce_myeloid[,(!(sce_myeloid$M_cluster == "none"))]

sce_tumor$info <- sce_tumor$celltype
sce_Tcells$info <- sce_Tcells$celltype
sce_myeloid$info <- sce_myeloid$celltype

```

## Neighborhood aggregation

```{r generate neighborhood composition for each cell}

# Aggregate across neighbors and remove cells without neighbours
sce_tumor <- aggregateNeighbors(sce_tumor, colPairName = "expansion_60", 
                              aggregate_by = "metadata", count_by = "info",
                              name = "aggr_expansion_60", proportions = FALSE)
sce_Tcells <- aggregateNeighbors(sce_Tcells, colPairName = "expansion_60", 
                              aggregate_by = "metadata", count_by = "info",
                              name = "aggr_expansion_60", proportions = FALSE)
sce_myeloid <- aggregateNeighbors(sce_myeloid, colPairName = "expansion_60", 
                              aggregate_by = "metadata", count_by = "info",
                              name = "aggr_expansion_60", proportions = FALSE)


tumor_counts_60 <- sce_tumor$aggr_expansion_60
rownames(tumor_counts_60) <- colnames(sce_tumor)
tumor_counts_60 <- tumor_counts_60[rowSums(as.matrix(tumor_counts_60)) != 0,]
tumor_fqs_60  <- log(prop.table(as.matrix(tumor_counts_60) + 1, 1), 2)
tumor_clr_60  <- as.matrix(tumor_fqs_60-rowMeans(tumor_fqs_60))

Tcell_counts_60 <- sce_Tcells$aggr_expansion_60
rownames(Tcell_counts_60) <- colnames(sce_Tcells)
Tcell_counts_60 <- Tcell_counts_60[rowSums(as.matrix(Tcell_counts_60)) != 0,]
Tcell_fqs_60  <- log(prop.table(as.matrix(Tcell_counts_60) + 1, 1), 2)
Tcell_clr_60  <- as.matrix(Tcell_fqs_60-rowMeans(Tcell_fqs_60))

myeloid_counts_60 <- sce_myeloid$aggr_expansion_60
rownames(myeloid_counts_60) <- colnames(sce_myeloid)
myeloid_counts_60 <- myeloid_counts_60[rowSums(as.matrix(myeloid_counts_60)) != 0,]
myeloid_fqs_60  <- log(prop.table(as.matrix(myeloid_counts_60) + 1, 1), 2)
myeloid_clr_60  <- as.matrix(myeloid_fqs_60-rowMeans(myeloid_fqs_60))

```

```{r Perform cluster sweep}

# Example is shwon here for the analysis of the tumor compartment and was performed alike for myeloid and T cells
# Perform cluster sweep
set.seed(220427)
clust_list_60 <- lapply(2:20, function(k){
  cur_km <- kmeans(tumor_clr_60, centers = k, iter.max = 50, nstart = 20)
  return(list(wss = cur_km$tot.withinss,
           clusters = cur_km$cluster))
})

sil_60 <- vapply(lapply(clust_list_60, `[[`, 2), 
              function(x) mean(approxSilhouette(tumor_clr_60, x)$width), 
              0)


# can be between -1 and 1 with 1 being optimal
ggplot(data.frame(k = rep(2:20, 3),
                  sil = sil_60)) +
    geom_point(aes(k, sil)) +
    theme_classic(base_size = 20) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    xlab("Cluster parameter combination") +
    ylab("Average silhouette width")

# measures compactness of a cluster, as small as possible
ggplot(data.frame(k = rep(2:20, 3),
                  wss = sapply(clust_list_60, `[[`, 1))) +
    geom_point(aes(k, wss)) +
    theme_classic(base_size = 20) +
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    xlab("Cluster parameter combination") +
    ylab("Total within cluster sum of squares")

```

```{r}
set.seed(220620)
tumor_cur_km_60 <- kmeans(tumor_clr_60, centers = 12, iter.max = 50, nstart = 20)

tumor_cn_60 <- rep(NA, ncol(sce_tumor))
names(tumor_cn_60) <- colnames(sce_tumor)
tumor_cn_60[rownames(tumor_counts_60)] <- tumor_cur_km_60$cluster
sce_tumor$tumor_cn_60 <- as.factor(tumor_cn_60)

Tcell_cur_km_60 <- kmeans(tumor_clr_60, centers = 14, iter.max = 50, nstart = 20)

Tcell_cn_60 <- rep(NA, ncol(sce_Tcells))
names(Tcell_cn_60) <- colnames(sce_Tcells)
Tcell_cn_60[rownames(Tcell_counts_60)] <- Tcell_cur_km_60$cluster
sce_Tcells$Tcell_cn_60 <- as.factor(Tcell_cn_60)

myeloid_cur_km_60 <- kmeans(myeloid_clr_60, centers = 9, iter.max = 50, nstart = 20)

myeloid_cn_60 <- rep(NA, ncol(sce_myeloid))
names(myeloid_cn_60) <- colnames(sce_myeloid)
myeloid_cn_60[rownames(myeloid_counts_60)] <- myeloid_cur_km_60$cluster
sce_myeloid$myeloid_cn_60 <- as.factor(myeloid_cn_60)

```

```{r Plotting, fig.width=15, fig.height=15}

# expansion 60
tumor_cur_dat <- prop.table(table(sce_tumor$tumor_cn_60, sce_tumor$info), margin = 1)
Tcell_cur_dat <- prop.table(table(sce_Tcells$Tcell_cn_60, sce_Tcells$info), margin = 1)
myeloid_cur_dat <- prop.table(table(sce_myeloid$myeloid_cn_60, sce_myeloid$info), margin = 1)

tumor_scaled <- as.data.frame(apply(tumor_cur_dat, MARGIN = 2, FUN = function(x) scale(x)))
Tcell_scaled <- as.data.frame(apply(Tcell_cur_dat, MARGIN = 2, FUN = function(x) scale(x)))
myeloid_scaled <- as.data.frame(apply(myeloid_cur_dat, MARGIN = 2, FUN = function(x) scale(x)))

# Exemplary plotting for tumor cells
ha <- HeatmapAnnotation(cluster = colnames(tumor_scaled),
                        col = list(cluster = cols_tumor_clusters),
                        show_legend = FALSE)

Heatmap(tumor_scaled,
        col = colorRamp2(c(-3, 0, 3), c("darkblue", "white", "darkred")),
        cluster_rows = FALSE,
        rect_gp = gpar(col = "grey", lwd = 0.5))


pheatmap(tumor_cur_dat, color = colorRampPalette(c("dark blue", "white", "dark red"))(100), 
         cluster_rows = FALSE, scale = "column")

```


```{r Differential abundance}

sce_myeloid$sample_type <- "M"
sce_myeloid$sample_type[which(sce_myeloid$Tissue.Type == "PT")] <- "PT"

# Prepare abundance object
sce_myeloid$patient_sample <- paste0(sce_myeloid$Patient.ID, "_", sce_myeloid$sample_type)
abundances <- table(sce_myeloid$myeloid_cn_60, sce_myeloid$patient_sample)
abundances <- unclass(abundances)

meta <- colData(sce_myeloid)[match(colnames(abundances), sce_myeloid$patient_sample),]
rownames(meta) <- meta$patient_sample

cur_patients <- unique(sce_myeloid$Patient.ID[sce_myeloid$sample_type == "M"])
cur_meta <- meta[meta$Patient.ID %in% cur_patients,]
cur_meta <- cur_meta[grepl("PT|M", cur_meta$sample_type),]
cur_ab <- abundances[,rownames(cur_meta)]

# For a specific tissue type
sample_type <- factor(meta$sample_type)
meta$sample_type <- relevel(x=sample_type, ref = "PT")
y.ab <- DGEList(abundances, samples = meta, group = meta$sample_type)

# Define the design matrix for the model: Add Patient ID to the model to account for matched design, add tissue type as an additive factor
design <- model.matrix(~Patient.ID + sample_type, data = y.ab$samples)

# Estimate NB and QL dispersion
y.ab <- estimateDisp(y.ab, design, trend="none")
summary(y.ab$common.dispersion)
fit.ab <- glmQLFit(y.ab, design, robust=TRUE, abundance.trend=FALSE)
summary(fit.ab$var.prior)


# Test for differential abundance of cell types in PT vs met tissue and plot
res <- glmQLFTest(fit.ab, coef=colnames(fit.ab)[ncol(fit.ab)])
summary(decideTests(res))
DA <- res$table

DA$celltype <- rownames(DA)
DA$sign <- ifelse(DA$PValue < 0.05, "yes", "no")

# Sort by logFC
order <- rev(rownames(DA))
DA <- DA[order,]
DA$celltype <- factor(DA$celltype, levels = DA$celltype)

ggplot(DA, aes(celltype, y = logFC))+
  geom_col(aes(fill=sign))+
  scale_fill_manual(values = c("grey", "darkgreen"))+
  labs(y=paste0("logFC"), x="Community")+
  coord_flip() +
  labs(fill="significant") +
  theme(panel.background=element_blank(), panel.border = element_rect(colour = "black", fill=NA, size=1))

```

```{r Differential abundance for specific tissues - Example}

# Prepare abundance object
sce_myeloid$patient_tissue <- paste0(sce_myeloid$Patient.ID, "_", sce_myeloid$Tissue.Type)
abundances <- table(sce_myeloid$myeloid_cn_60, sce_myeloid$patient_tissue)
abundances <- unclass(abundances)

meta <- colData(sce_myeloid)[match(colnames(abundances), sce_myeloid$patient_tissue),]
rownames(meta) <- meta$patient_tissue

cur_patients <- unique(sce_myeloid$Patient.ID[sce_myeloid$Tissue.Type == "Brain"])
cur_meta <- meta[meta$Patient.ID %in% cur_patients,]
cur_meta <- cur_meta[grepl("PT|Brain", cur_meta$Tissue.Type),]
cur_ab <- abundances[,rownames(cur_meta)]

# For a specific tissue type
Tissue.Type <- factor(cur_meta$Tissue.Type)
cur_meta$Tissue.Type <- relevel(x=Tissue.Type, ref = "PT")
y.ab <- DGEList(cur_ab, samples=cur_meta, group = cur_meta$Tissue.Type)

# Define the design matrix for the model: Add Patient ID to the model to account for matched design, add tissue type as an additive factor
design <- model.matrix(~Patient.ID + Tissue.Type, data = y.ab$samples)

# Estimate NB and QL dispersion
y.ab <- estimateDisp(y.ab, design, trend="none")
summary(y.ab$common.dispersion)
fit.ab <- glmQLFit(y.ab, design, robust=TRUE, abundance.trend=FALSE)
summary(fit.ab$var.prior)


# Test for differential abundance of cell types in PT vs met tissue and plot
res <- glmQLFTest(fit.ab, coef=colnames(fit.ab)[ncol(fit.ab)])
summary(decideTests(res))
DA <- res$table

DA$celltype <- rownames(DA)
DA$sign <- ifelse(DA$PValue < 0.05, "yes", "no")

# Sort by logFC
order <- rev(rownames(DA))
DA <- DA[order,]
DA$celltype <- factor(DA$celltype, levels = DA$celltype)

ggplot(DA, aes(celltype, y = logFC))+
  geom_col(aes(fill=sign))+
  scale_fill_manual(values = c("grey", "darkgreen"))+
  labs(y=paste0("logFC"), x="Community")+
  coord_flip() +
  labs(fill="significant") +
  theme(panel.background=element_blank(), panel.border = element_rect(colour = "black", fill=NA, size=1))

```


```{r visualization of cellular neighborhoods}

plotSpatial(sce_myeloid[,which(sce_myeloid$Tissue.Type == "Brain")],
            img_id = "ImageNumber",
            coords = c("Center_X", "Center_Y"),
            node_color_by = "myeloid_cn_60",
            node_size_fix = 0.3) +
  scale_color_manual(values = c(rep("grey",7), "red", rep("grey",9)))

```




